const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const ADD_INGREDIENT = 'ADD_INGREDIENT';
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';


export
{
  INCREMENT,
  DECREMENT,
  ADD_INGREDIENT,
  REMOVE_INGREDIENT
};
